export const APP_NAME = 'omdb-viewer'
export const OMDB_URL = 'https://www.omdbapi.com/'
export const QUERY_DELAY = 300
export const ESC_KEY = 27
export const TITLE_COLOR = '#210d87'
export const BANNER_TITLE = 'Open Movie Database Browser'
export const FETCH_TIMEOUT = 10000
export const OMDB_API_URL = 'https://www.omdbapi.com'
export const OMDB_API_KEY = 'fbfcb8c7'
